FROM        --platform=$TARGETOS/$TARGETARCH alpine:latest

LABEL       maintainer="matthew@stellarstack.io"

LABEL       org.opencontainers.image.source="https://github.com/stellarstack/yolks"
LABEL       org.opencontainers.image.licenses=MIT

RUN         apk add --update --no-cache ca-certificates curl git jq wget
